name: Test Conditions

on:
  # @mhoffrog - allow manual trigger on this fork
  workflow_dispatch:
    inputs:
      run-step-10:
        description: 'Run step 10'
        type: boolean
        required: false
        default: 'false'
      run-step-20:
        description: 'Run step 20'
        type: boolean
        required: false
        default: 'false'
  #pull_request:
  push:
    branches:
      - 'eval/gh_actions'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        # @mhoffrog - ubuntu-latest only on this fork
        #os: [ubuntu-latest, macos-15-intel, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log context
        shell: bash
        run: |
          echo "Triggered by github.event_name: '${{ github.event_name }}'"
          echo "github.event.inputs.run-step-10: '${{ github.event.inputs.run-step-10 }}'"
          echo "github.event.inputs.run-step-20: '${{ github.event.inputs.run-step-20 }}'"

      - name: Step 10
        if: ${{ github.event.inputs.run-step-10 == '' || github.event.inputs.run-step-10 == 'true' }}
        shell: bash
        run: |
          echo "Run step 10 triggered by event: ${{ github.event_name }}"

      - name: Step 20
        if: ${{ github.event.inputs.run-step-20 == '' || github.event.inputs.run-step-20 == 'true' }}
        shell: bash
        run: |
          echo "Run step 20 triggered by event: ${{ github.event_name }}"
